[[language]]
name = "python"
auto-format = true
language-servers = [
  { name = "ty", except-features = [ "goto-definition", "goto-declaration", "goto-type-definition", "goto-reference", "goto-implementation", "completion", "hover" ] },
  { name = "ruff" },
  { name = "jedi", except-features = [ "goto-definition", "goto-declaration", "goto-type-definition", "goto-reference", "goto-implementation", "hover", "completion" ] },
  { name = "pylsp", except-features = [ "diagnostics" ] }
]


